name: Lint

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  black-and-flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python3 -m pip install tox
      - name: Run linting
        run: |
            tox -e lint
